### ISSUE TITLE
"Error 500: Internal Server Error" in "Zuteilungen anzeigen" 

### ISSUE THREAD

**Issue by sternik77** [svpbde/svpb#46]
**Description:**
"Error 500: Internal Server Error"-Site is shown when you click "Zeiten" in "Zuteilungen anzeigen" 

**How to Reproduce:**
- Log in to the main.svpb.de
- Go to "Home"
- Click "Zuteilungen anzeigen"
- Click "Zeiten" 
-> ERROR: Website "Error 500: Internal Server Error" is shown

**Severity:** 
- Minor

**Acceptance Criteria:**
- "Error 500: Internal Server Error" is not shown after click "Zeiten in "Zuteilungen anzeigen"

**Comment by transistortim** [comment]
Wow, our first issue from outside the core team, thanks for raising it! :tada: 

Clicking on "Zeiten" triggers code in the package django_tables2 to order the table. The actual ordering happens on the database level, before the table is rendered. However, the value for "Zeiten" is not stored in the database, but calculated by a Python [method of the database model](https://github.com/svpbde/svpb/blob/8c2db3ddbd17a24a542f15cc16731ddb8b68fa15/arbeitsplan/models.py#L511). So it's not possible to sort by this column and it should have been marked with `orderable=False`, which is what I just did.

We'll try to deploy the fix on the weekend.
